extends GutTest
## The server's name filter deletes the characters the game font cannot draw by looking them up in
## firebase/functions/src/name_glyphs.json (generated by tools/firebase/gen_name_glyphs.sh from NameFilter itself). This test
## asks NameFilter about every code point of the Basic Multilingual Plane and compares: when the font, its import or NameFilter
## changes and the table is not regenerated, the server would drop a different set of characters than the game.

const TABLE: String = "../firebase/functions/src/name_glyphs.json"


func _table_path() -> String:
	return ProjectSettings.globalize_path("res://").path_join(TABLE).simplify_path()


func _load_ranges() -> Array:
	var f: FileAccess = FileAccess.open(_table_path(), FileAccess.READ)
	if f == null:
		return []
	var parsed: Variant = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY or typeof((parsed as Dictionary).get("ranges", null)) != TYPE_ARRAY:
		return []
	return (parsed as Dictionary)["ranges"] as Array


func test_the_table_matches_what_the_game_draws_for_every_code_point() -> void:
	var ranges: Array = _load_ranges()
	if ranges.is_empty():
		fail_test("firebase/functions/src/name_glyphs.json is missing or unreadable (run tools/firebase/gen_name_glyphs.sh)")
		return
	var listed: Dictionary = {}
	var previous_end: int = -2
	for r: Variant in ranges:
		var pair: Array = r as Array
		var lo: int = pair[0]
		var hi: int = pair[1]
		assert_lte(lo, hi, "ranges are ordered")
		assert_gt(lo, previous_end + 1, "ranges are sorted and not touching")
		previous_end = hi
		for code: int in range(lo, hi + 1):
			listed[code] = true
	var wrong: Array[String] = []
	for code2: int in range(0, 0x10000):
		var game: bool = NameFilter._drawable_uncached(code2)
		if game != listed.has(code2):
			wrong.append("U+%04X game=%s table=%s" % [code2, game, listed.has(code2)])
			if wrong.size() >= 10:
				break
	assert_eq(wrong, [], "the glyph table is out of date: run tools/firebase/gen_name_glyphs.sh and commit name_glyphs.json")


func test_the_table_has_what_names_need() -> void:
	var listed: Dictionary = {}
	for r: Variant in _load_ranges():
		for code: int in range((r as Array)[0] as int, ((r as Array)[1] as int) + 1):
			listed[code] = true
	for c: String in "AZaz09 -.'#":
		assert_true(listed.has(c.unicode_at(0)), "'%s' is kept" % c)
	for code2: int in [0x00, 0x1F, 0x7F, 0x9F, 0xAD, 0x200B, 0x202E, 0xFEFF, 0xD800, 0xFFFF]:
		assert_false(listed.has(code2), "U+%04X is dropped" % code2)
