extends Node
## AudioDirector (autoload, docs/ARCHITECTURE.md section 33): every sound the game makes.
##
## The simulation never makes sound; the battle controller calls `on_event(e)` once for every timeline
## event it plays, and this node maps the event to a sound. Nothing here influences the game.
##
## Buses (default_bus_layout.tres): Master -> SFX, UI, Music. The settings screen's "Sound effects" volume and
## on/off drive the SFX bus, "UI sounds" on/off the UI bus (which also follows the effects volume and goes
## silent with effects off), "Music" volume and on/off the Music bus. They live in ShowSettings and are
## re-applied whenever they change (see `apply_settings`).
##
## Sounds are 16-bit mono WAVs generated by tools/sfx/gen_sfx.py (presets in tools/sfx/presets.json) and are
## preloaded once below. Playback uses fixed pools of AudioStreamPlayer nodes: MAX_VOICES for effects (the
## quietest/oldest voice is stolen when a more important sound arrives, and a new sound that is less
## important than everything playing is dropped), UI_VOICES for UI sounds, plus one node each for the
## two loops (well hum, fire crackle) and the music. No node or stream is created while playing.
## Pitch is jittered by +-PITCH_JITTER so repeated sounds do not machine-gun. Playback speed 2x only shortens
## the minimum gap between equal sounds (more overlap), it never changes pitch.
##
## HOW TO ADD MUSIC: drop an OGG (Vorbis) file into game/assets/music/, add a line to MUSIC_TRACKS below, e.g.
##     "menu": "res://assets/music/menu.ogg",
## and call AudioDirector.play_music("menu") where it should start (AudioDirector.stop_music() to end it).
## In the OGG's Import dock tick "Loop" so it repeats. The Music bus and the Settings "Music" volume/switch
## already work, so no other change is needed. (There is no track yet, so play_music() is a silent no-op.)

## Effect volume (dB, before the SFX bus), priority (1-10: how important when the pool is full) and the
## minimum gap in milliseconds between two plays of the same sound.
const SOUNDS: Dictionary = {
	"fire_light": {"s": preload("res://assets/sfx/fire_light.wav"), "db": -6.0, "pri": 3, "gap": 40},
	"fire_medium": {"s": preload("res://assets/sfx/fire_medium.wav"), "db": -5.0, "pri": 4, "gap": 40},
	"fire_heavy": {"s": preload("res://assets/sfx/fire_heavy.wav"), "db": -3.0, "pri": 5, "gap": 40},
	"beam_zap": {"s": preload("res://assets/sfx/beam_zap.wav"), "db": -4.0, "pri": 5, "gap": 60},
	"explosion_small": {"s": preload("res://assets/sfx/explosion_small.wav"), "db": -4.0, "pri": 5, "gap": 35},
	"explosion_medium": {"s": preload("res://assets/sfx/explosion_medium.wav"), "db": -3.0, "pri": 7, "gap": 40},
	"explosion_large": {"s": preload("res://assets/sfx/explosion_large.wav"), "db": -2.0, "pri": 9, "gap": 60},
	"explosion_nuke": {"s": preload("res://assets/sfx/explosion_nuke.wav"), "db": 0.0, "pri": 10, "gap": 80},
	"terrain_crumble": {"s": preload("res://assets/sfx/terrain_crumble.wav"), "db": -8.0, "pri": 3, "gap": 150},
	"dirt_thud": {"s": preload("res://assets/sfx/dirt_thud.wav"), "db": -5.0, "pri": 3, "gap": 70},
	"sludge_pour": {"s": preload("res://assets/sfx/sludge_pour.wav"), "db": -7.0, "pri": 4, "gap": 300},
	"anchor_clank": {"s": preload("res://assets/sfx/anchor_clank.wav"), "db": -4.0, "pri": 5, "gap": 100},
	"shield_up": {"s": preload("res://assets/sfx/shield_up.wav"), "db": -5.0, "pri": 5, "gap": 80},
	"shield_hit": {"s": preload("res://assets/sfx/shield_hit.wav"), "db": -5.0, "pri": 4, "gap": 50},
	"shield_break": {"s": preload("res://assets/sfx/shield_break.wav"), "db": -3.0, "pri": 6, "gap": 80},
	"repulsor_pulse": {"s": preload("res://assets/sfx/repulsor_pulse.wav"), "db": -6.0, "pri": 4, "gap": 100},
	"chute_pop": {"s": preload("res://assets/sfx/chute_pop.wav"), "db": -5.0, "pri": 5, "gap": 100},
	"repair_chime": {"s": preload("res://assets/sfx/repair_chime.wav"), "db": -5.0, "pri": 6, "gap": 150},
	"money_gain": {"s": preload("res://assets/sfx/money_gain.wav"), "db": -9.0, "pri": 2, "gap": 140},
	"money_loss": {"s": preload("res://assets/sfx/money_loss.wav"), "db": -9.0, "pri": 2, "gap": 140},
	"tank_destroyed": {"s": preload("res://assets/sfx/tank_destroyed.wav"), "db": -2.0, "pri": 8, "gap": 80},
	"round_win": {"s": preload("res://assets/sfx/round_win.wav"), "db": -5.0, "pri": 9, "gap": 500},
	"match_win": {"s": preload("res://assets/sfx/match_win.wav"), "db": -4.0, "pri": 10, "gap": 500},
	"turn_blip": {"s": preload("res://assets/sfx/turn_blip.wav"), "db": -9.0, "pri": 2, "gap": 120},
	"cpu_think_tick": {"s": preload("res://assets/sfx/cpu_think_tick.wav"), "db": -18.0, "pri": 1, "gap": 100},
	"ui_tap": {"s": preload("res://assets/sfx/ui_tap.wav"), "db": -8.0, "pri": 5, "gap": 45},
	"ui_back": {"s": preload("res://assets/sfx/ui_back.wav"), "db": -8.0, "pri": 5, "gap": 45},
	"ui_purchase": {"s": preload("res://assets/sfx/ui_purchase.wav"), "db": -6.0, "pri": 6, "gap": 90},
	"ui_locked": {"s": preload("res://assets/sfx/ui_locked.wav"), "db": -7.0, "pri": 6, "gap": 120},
	"fire_crackle": {"s": preload("res://assets/sfx/fire_crackle.wav"), "db": -6.0, "pri": 3, "gap": 0},
	"well_hum": {"s": preload("res://assets/sfx/well_hum.wav"), "db": -12.0, "pri": 3, "gap": 0},
}

## Music tracks (none yet): name -> "res://assets/music/<file>.ogg". See the header.
const MUSIC_TRACKS: Dictionary = {}

const BUS_MASTER: String = "Master"
const BUS_SFX: String = "SFX"
const BUS_UI: String = "UI"
const BUS_MUSIC: String = "Music"
const BUS_NAMES: PackedStringArray = ["SFX", "UI", "Music"]

const MAX_VOICES: int = 12
const UI_VOICES: int = 4
const PITCH_JITTER: float = 0.04
## A same-priority voice may only be stolen once it has played this long (ms).
const STEAL_MIN_AGE_MS: int = 80
const MIN_DB: float = -80.0
## Silent-bus threshold for the loops' fades.
const SILENT_DB: float = -60.0

## How long the fire crackle lasts, matching FlameField.DURATION, and when it starts to fade (fraction).
const CRACKLE_SECONDS: float = 1.5
const CRACKLE_FADE_FROM: float = 0.45
const HUM_FADE_IN: float = 0.3
const HUM_FADE_OUT: float = 0.6
## The computer's "thinking" tick: one tick per this many seconds.
const THINK_INTERVAL: float = 0.34

## Explosion radius (cells) -> size class: below SMALL_MAX small, below MEDIUM_MAX medium, below LARGE_MAX
## large, otherwise nuke. (Spark Dart 14 ... Pulse Missile 28 ... Hyperpulse 44 ... Nova Core 90 ... Supernova 160.)
const SMALL_MAX: int = 26
const MEDIUM_MAX: int = 60
const LARGE_MAX: int = 120
## UI buttons with these node names get the "back" sound instead of the "tap".
const BACK_NAMES: PackedStringArray = ["Back", "Close", "Cancel", "Resume", "Backdrop"]
## Meta on a button: "none" (stay silent) or a UI sound name ("tap", "back", "purchase", "locked").
const UI_SOUND_META: String = "ui_sound"

## Test hook: when true every sound that is requested is appended to `played_log` (even if the pool refused it).
var record_log: bool = false
var played_log: Array[String] = []
## Counters: sounds played, stolen voices, dropped (pool full or too soon).
var stats: Dictionary = {"played": 0, "stolen": 0, "dropped": 0}

var _voices: Array[AudioStreamPlayer] = []
var _voice_pri: PackedInt32Array = PackedInt32Array()
var _voice_start: PackedInt32Array = PackedInt32Array()
var _ui_voices: Array[AudioStreamPlayer] = []
var _ui_next: int = 0
var _hum: AudioStreamPlayer = null
var _crackle: AudioStreamPlayer = null
var _music: AudioStreamPlayer = null
var _rng: RandomNumberGenerator = RandomNumberGenerator.new()
var _last_play: Dictionary = {}
## Wells that exist (owner id -> true), the hum plays while there is one.
var _wells: Dictionary = {}
var _hum_on: bool = false
var _hum_db: float = MIN_DB
var _crackle_t: float = -1.0
var _think_acc: float = 0.0
## The settings last applied to the buses (compared one by one: no allocation per sound).
var _a_sfx_vol: int = -1
var _a_sfx_on: bool = true
var _a_music_vol: int = -1
var _a_music_on: bool = true
var _a_ui_on: bool = true
var _music_track: String = ""


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_rng.seed = 20260101
	_ensure_buses()
	for i: int in range(MAX_VOICES):
		_voices.append(_make_player("Voice%d" % i, BUS_SFX))
	_voice_pri.resize(MAX_VOICES)
	_voice_start.resize(MAX_VOICES)
	for i: int in range(UI_VOICES):
		_ui_voices.append(_make_player("UiVoice%d" % i, BUS_UI))
	_hum = _make_loop_player("WellHum", "well_hum")
	_crackle = _make_loop_player("FireCrackle", "fire_crackle")
	_music = _make_player("Music", BUS_MUSIC)
	SettingsStore.ensure_loaded()
	apply_settings()
	get_tree().node_added.connect(_on_node_added)
	set_process(false)


# ======================================================================================
# Public API
# ======================================================================================

## One timeline event of a played-back timeline (ARCHITECTURE sections 10, 20, 21, 25). `match_over` is true
## when the match is decided by this timeline, so its round_end plays the match jingle instead.
func on_event(e: Dictionary, match_over: bool = false) -> void:
	match e.get("type", ""):
		"round_start":
			_wells.clear()
			_update_hum()
			_stop_crackle()
		"well_on":
			_wells[e.get("owner", 0)] = true
			_update_hum()
		"well_off":
			_wells.erase(e.get("owner", 0))
			_update_hum()
		"flames":
			_start_crackle()
	var key: String = sound_for_event(e, match_over)
	if key != "":
		play_sfx(key)


## The sound key an event plays ("" = silent). Pure, so the mapping is testable.
static func sound_for_event(e: Dictionary, match_over: bool = false) -> String:
	match e.get("type", ""):
		"fire":
			return fire_key(e.get("weapon", "") as String)
		"explosion":
			return explosion_key(int(e.get("radius", 0)))
		"terrain_settle":
			return "terrain_crumble" if int(e.get("falls", 0)) > 0 else ""
		"tunnel":
			return "terrain_crumble"
		"terrain_add":
			return "dirt_thud"
		"terrain_pour":
			return "sludge_pour"
		"tank_drag":
			return "anchor_clank" if int(e.get("to_x", 0)) != int(e.get("from_x", 0)) else ""
		"damage":
			return "dirt_thud" if e.get("cause", "") == "fall" else ""
		"shield_on":
			return "shield_up"
		"shield_hit":
			return "shield_hit"
		"shield_down":
			return "shield_break"
		"repulsor_on":
			return "repulsor_pulse"
		"chute":
			return "chute_pop"
		"repair":
			return "repair_chime"
		"money":
			var reason: String = e.get("reason", "") as String
			if reason == "buy" or reason == "sell":
				return ""
			return "money_gain" if int(e.get("delta", 0)) > 0 else "money_loss"
		"tank_destroyed":
			return "tank_destroyed"
		"turn":
			return "turn_blip"
		"round_end":
			if int(e.get("winner", -1)) < 0:
				return ""
			return "match_win" if match_over else "round_win"
	# projectile, projectile_end, terrain_carve, wind, beam (its sound is the fire event's), tank_fall,
	# tank_move, well_on/off (the hum loop), flames (the crackle loop), ready, repulsor_down, round_start.
	return ""


## Explosion radius -> "explosion_small" / "_medium" / "_large" / "_nuke".
static func explosion_key(radius: int) -> String:
	if radius < SMALL_MAX:
		return "explosion_small"
	if radius < MEDIUM_MAX:
		return "explosion_medium"
	if radius < LARGE_MAX:
		return "explosion_large"
	return "explosion_nuke"


## Weapon id -> fire sound, by behaviour (and size): "fire_light" / "_medium" / "_heavy" / "beam_zap".
static func fire_key(weapon_id: String) -> String:
	if not WeaponDefs.has(weapon_id):
		return "fire_medium"
	var def: Dictionary = WeaponDefs.get_def(weapon_id)
	var radius: int = int(def.get("r", 0))
	match def.get("behavior", ""):
		"beam":
			return "beam_zap"
		"explode":
			return "fire_light" if radius < 20 else ("fire_medium" if radius < MEDIUM_MAX else "fire_heavy")
		"roller":
			return "fire_light" if radius < 40 else "fire_medium"
		"static":
			return "fire_light"
		"dirt":
			return "fire_medium" if radius < 60 else "fire_heavy"
		"fire":
			return "fire_medium" if int(def.get("points", 0)) < 100 else "fire_heavy"
		"sludge", "well":
			return "fire_heavy"
	return "fire_medium"  # splitter, seeker, tunneler, anchor


## Plays an effect (a key of SOUNDS). Returns true when it started a voice.
func play_sfx(key: String, volume_offset_db: float = 0.0) -> bool:
	_sync_settings()
	if not SOUNDS.has(key):
		push_warning("AudioDirector: unknown sound '%s'" % key)
		return false
	var spec: Dictionary = SOUNDS[key]
	if record_log:
		played_log.append(key)
	if _too_soon(key, spec["gap"] as int):
		stats["dropped"] += 1
		return false
	var pri: int = spec["pri"]
	var i: int = _acquire_voice(pri)
	if i < 0:
		stats["dropped"] += 1
		return false
	var p: AudioStreamPlayer = _voices[i]
	p.stream = spec["s"] as AudioStream
	p.volume_db = (spec["db"] as float) + volume_offset_db
	p.pitch_scale = 1.0 + _rng.randf_range(-PITCH_JITTER, PITCH_JITTER)
	p.play()
	_voice_pri[i] = pri
	_voice_start[i] = Time.get_ticks_msec()
	stats["played"] += 1
	return true


## A UI sound by short name: "tap", "back", "purchase" or "locked" (or the full key, e.g. "ui_tap").
func play_ui(sound: String) -> bool:
	_sync_settings()
	var key: String = sound if sound.begins_with("ui_") else "ui_" + sound
	if not SOUNDS.has(key):
		push_warning("AudioDirector: unknown UI sound '%s'" % sound)
		return false
	if record_log:
		played_log.append(key)
	var spec: Dictionary = SOUNDS[key]
	if _is_bus_muted(BUS_UI) or _too_soon(key, spec["gap"] as int):
		stats["dropped"] += 1
		return false
	var p: AudioStreamPlayer = _ui_voices[_ui_next]
	_ui_next = (_ui_next + 1) % UI_VOICES
	p.stream = spec["s"] as AudioStream
	p.volume_db = spec["db"] as float
	p.pitch_scale = 1.0 + _rng.randf_range(-PITCH_JITTER, PITCH_JITTER)
	p.play()
	stats["played"] += 1
	return true


## The computer's thinking tick: call every frame of its think stage. No ticks when the CPU turn speed is
## Instant (there is no thinking to hear).
func think_tick(delta: float) -> void:
	if ShowSettings.cpu_speed_scale() <= 0.0:
		return
	_think_acc += delta
	if _think_acc >= THINK_INTERVAL:
		_think_acc = 0.0
		play_sfx("cpu_think_tick")


## Re-creates the set of wells the hum follows (after a rebuild or restore): the hum plays while any exists.
func sync_wells(owners: Array) -> void:
	_wells.clear()
	for o: Variant in owners:
		_wells[o] = true
	_update_hum()


## Silences the loops and the pool (the battle is closing).
func stop_all() -> void:
	_wells.clear()
	_update_hum()
	_stop_crackle()
	for p: AudioStreamPlayer in _voices:
		p.stop()
	_hum.stop()
	_hum_db = MIN_DB
	_hum_on = false


## Test hook: back to a quiet, empty state (no voices, loops, log, counters or gap memory).
func reset_for_tests() -> void:
	stop_all()
	for p: AudioStreamPlayer in _ui_voices:
		p.stop()
	_last_play.clear()
	played_log.clear()
	record_log = false
	stats["played"] = 0
	stats["stolen"] = 0
	stats["dropped"] = 0
	_think_acc = 0.0


func is_hum_playing() -> bool:
	return _hum_on


func is_crackle_playing() -> bool:
	return _crackle_t >= 0.0


## Number of effect voices busy right now.
func active_voices() -> int:
	var n: int = 0
	for p: AudioStreamPlayer in _voices:
		if p.playing:
			n += 1
	return n


func play_music(track: String) -> void:
	if not MUSIC_TRACKS.has(track) or _music_track == track:
		return
	var stream: AudioStream = load(MUSIC_TRACKS[track] as String) as AudioStream
	if stream == null:
		push_warning("AudioDirector: cannot load music '%s'" % track)
		return
	_music_track = track
	_music.stream = stream
	_music.play()


func stop_music() -> void:
	_music_track = ""
	_music.stop()


## Reads ShowSettings into the buses (volume 0-100 -> dB, switches -> mute). Called whenever a setting changes;
## sounds also check it themselves, so a change made any other way is picked up at the next sound.
func apply_settings() -> void:
	_ensure_buses()
	var sfx_db: float = volume_to_db(ShowSettings.sfx_volume)
	var sfx_muted: bool = not ShowSettings.sfx_on
	_set_bus(BUS_SFX, sfx_db, sfx_muted)
	# UI sounds follow the effects volume and are silent when effects are off.
	_set_bus(BUS_UI, sfx_db, sfx_muted or not ShowSettings.ui_sounds)
	_set_bus(BUS_MUSIC, volume_to_db(ShowSettings.music_volume), not ShowSettings.music_on)
	_a_sfx_vol = ShowSettings.sfx_volume
	_a_sfx_on = ShowSettings.sfx_on
	_a_music_vol = ShowSettings.music_volume
	_a_music_on = ShowSettings.music_on
	_a_ui_on = ShowSettings.ui_sounds


## 0..100 -> dB (linear amplitude), 0 = silent.
static func volume_to_db(volume: int) -> float:
	if volume <= 0:
		return MIN_DB
	return maxf(linear_to_db(float(clampi(volume, 0, 100)) / 100.0), MIN_DB)


# ======================================================================================
# Pool and loops
# ======================================================================================

func _make_player(player_name: String, bus: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.name = player_name
	p.bus = bus
	add_child(p)
	return p


## A loop player: the WAV's loop is switched on here (the import leaves it off), over the whole file.
func _make_loop_player(player_name: String, key: String) -> AudioStreamPlayer:
	var p: AudioStreamPlayer = _make_player(player_name, BUS_SFX)
	var stream: AudioStreamWAV = (SOUNDS[key] as Dictionary)["s"] as AudioStreamWAV
	stream.loop_mode = AudioStreamWAV.LOOP_FORWARD
	stream.loop_begin = 0
	stream.loop_end = stream.data.size() / 2  # 16-bit mono: samples
	p.stream = stream
	return p


## Index of a free voice, or one to steal (the least important, then the oldest), or -1 for none.
func _acquire_voice(pri: int) -> int:
	var victim: int = -1
	var now: int = Time.get_ticks_msec()
	for i: int in range(MAX_VOICES):
		if not _voices[i].playing:
			return i
		if victim < 0 or _voice_pri[i] < _voice_pri[victim] \
				or (_voice_pri[i] == _voice_pri[victim] and _voice_start[i] < _voice_start[victim]):
			victim = i
	if _voice_pri[victim] < pri or (_voice_pri[victim] == pri and now - _voice_start[victim] > STEAL_MIN_AGE_MS):
		stats["stolen"] += 1
		return victim
	return -1


## Equal sounds closer than `gap` ms (shorter at 2x playback speed) are one sound: it avoids phasing and a
## burst of identical voices (a splitter's children, a row of money pops).
func _too_soon(key: String, gap: int) -> bool:
	if gap <= 0:
		return false
	var now: int = Time.get_ticks_msec()
	var scaled: int = roundi(float(gap) / maxf(ShowSettings.playback_speed, 1.0))
	if _last_play.has(key) and now - (_last_play[key] as int) < scaled:
		return true
	_last_play[key] = now
	return false


func _update_hum() -> void:
	var want: bool = not _wells.is_empty()
	if want and not _hum_on:
		_sync_settings()
		_hum_on = true
		if not _hum.playing:
			_hum_db = MIN_DB
			_hum.volume_db = _hum_db
			_hum.play()
		_wake()
	elif not want and _hum_on:
		_hum_on = false  # fades out in _process, then stops
		_wake()


func _start_crackle() -> void:
	_sync_settings()
	_crackle_t = 0.0
	if not _crackle.playing:
		_crackle.volume_db = (SOUNDS["fire_crackle"] as Dictionary)["db"] as float
		_crackle.play()
	_wake()


func _stop_crackle() -> void:
	_crackle_t = -1.0
	_crackle.stop()


func _wake() -> void:
	if is_inside_tree():
		set_process(true)


func _process(delta: float) -> void:
	_sync_settings()
	var busy: bool = false
	# Well hum: fade in while wells exist, fade out after the last one is gone.
	var hum_full: float = (SOUNDS["well_hum"] as Dictionary)["db"] as float
	var span: float = absf(hum_full - MIN_DB)
	if _hum_on:
		if _hum_db < hum_full:
			_hum_db = move_toward(_hum_db, hum_full, span / HUM_FADE_IN * delta)
			_hum.volume_db = _hum_db
			busy = true
	elif _hum.playing:
		_hum_db = move_toward(_hum_db, MIN_DB, span / HUM_FADE_OUT * delta)
		_hum.volume_db = _hum_db
		if _hum_db <= SILENT_DB:
			_hum.stop()
			_hum_db = MIN_DB
		else:
			busy = true
	# Fire crackle: full at first, fades out with the flames.
	if _crackle_t >= 0.0:
		_crackle_t += delta
		var k: float = _crackle_t / CRACKLE_SECONDS
		if k >= 1.0:
			_stop_crackle()
		else:
			var fade: float = 1.0 - smoothstep(CRACKLE_FADE_FROM, 1.0, k)
			_crackle.volume_db = (SOUNDS["fire_crackle"] as Dictionary)["db"] as float + (linear_to_db(maxf(fade, 0.001)))
			busy = true
	if not busy:
		set_process(false)  # a steady hum needs no per-frame work; settings are checked at each sound


# ======================================================================================
# Buses and settings
# ======================================================================================

## Builds the buses if the project's layout is missing (a test project, a stripped export).
func _ensure_buses() -> void:
	for n: String in BUS_NAMES:
		if AudioServer.get_bus_index(n) < 0:
			AudioServer.add_bus()
			var idx: int = AudioServer.bus_count - 1
			AudioServer.set_bus_name(idx, n)
			AudioServer.set_bus_send(idx, BUS_MASTER)


func _set_bus(bus: String, db: float, muted: bool) -> void:
	var idx: int = AudioServer.get_bus_index(bus)
	if idx < 0:
		return
	AudioServer.set_bus_volume_db(idx, db)
	AudioServer.set_bus_mute(idx, muted)


func _is_bus_muted(bus: String) -> bool:
	var idx: int = AudioServer.get_bus_index(bus)
	return idx < 0 or AudioServer.is_bus_mute(idx)


func bus_index(bus: String) -> int:
	return AudioServer.get_bus_index(bus)


func _sync_settings() -> void:
	if _a_sfx_vol != ShowSettings.sfx_volume or _a_sfx_on != ShowSettings.sfx_on \
			or _a_music_vol != ShowSettings.music_volume or _a_music_on != ShowSettings.music_on \
			or _a_ui_on != ShowSettings.ui_sounds:
		apply_settings()


# ======================================================================================
# UI sounds for every button
# ======================================================================================

## Every BaseButton that enters the tree gets a tap sound on `pressed`, so no screen needs wiring. A button
## opts out or picks another sound with set_meta("ui_sound", "none" | "back" | "purchase" | "locked").
func _on_node_added(node: Node) -> void:
	if not (node is BaseButton) or node is FineButton or node is FireButton:
		return
	var b: BaseButton = node
	var cb: Callable = _on_button_pressed.bind(b)
	if not b.pressed.is_connected(cb):
		b.pressed.connect(cb)


func _on_button_pressed(b: BaseButton) -> void:
	var sound: String = b.get_meta(UI_SOUND_META, "") as String
	if sound == "none":
		return
	if sound == "":
		sound = "back" if BACK_NAMES.has(String(b.name)) else "tap"
	play_ui(sound)
